Copyright Tarter, Herasymov, Priebracha 2025

Finding minimal recurrence:

In [ ]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0


def backTest(upper):
    out = pd.DataFrame(columns=['BitCount', 'sampleSize', 'Time'])

    for i in range(upper-1):
        digitLength = 10**(i+1)
        sampleSize = 100

        tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
        for k in range(sampleSize): #generate the test cases
            tests.loc[k] = genSeq(4,digitLength)
        testList = tests['Test Case'].to_list() #send each test case to a list

        def decode(sequence, tests, l):
            n = len(sequence) #get length
            factors = []
            for j in range(n): #find factors ### O(n)
                if n % (j+1) == 0:
                    factors += [n/(j+1)]
            factors.sort()
            options = {}
            for i in range(len(factors)-1,0,-1): ####O(log(n))
                rec = sequence[int(n - factors[i]):n] #isolate the recurrence
                trial = f'{rec}'*2 #concat to make the trial
                if trial == str(tests.loc[l,'Test Case'])[int(n - 2*factors[i]):n]: #tests if the trial works
                    options.update({len(rec):rec})
            return options[min(options)]

        l = 0
        for sequence in testList:
            start = time.time()
            tests.loc[l,'Solution'] = decode(sequence,tests,l)
            end = time.time()
            tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
            tests.loc[l,'Solution Length'] = len(str(tests.loc[l,'Solution']))
            tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
            tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])
            if tests.loc[l,'Reccurence'] == tests.loc[l,'Solution']:
                tests.loc[l,'Works?'] = 1
            l += 1

        display(tests)
        out.loc[i]=[digitLength, sampleSize, np.mean(tests['Time'])]
        print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
    return out

out = backTest(7)
display(out)

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1100000000110000000011000000001100000000,1100000000,00,2,10,40,0,0.0
1,0000010010000001001000000100100000010010,0000010010,0000010010,10,10,40,1,0.0
2,1100000110110000011011000001101100000110,1100000110,1100000110,10,10,40,1,0.0
3,1101100111110110011111011001111101100111,1101100111,1101100111,10,10,40,1,0.0
4,0100101010010010101001001010100100101010,0100101010,10,2,10,40,0,0.0
...,...,...,...,...,...,...,...,...
95,1101000101110100010111010001011101000101,1101000101,01,2,10,40,0,0.0
96,0100000010010000001001000000100100000010,0100000010,0100000010,10,10,40,1,0.0
97,1001000000100100000010010000001001000000,1001000000,00,2,10,40,0,0.0
98,0011011100001101110000110111000011011100,0011011100,0011011100,10,10,40,1,0.0
99,1001011100100101110010010111001001011100,1001011100,1001011100,10,10,40,1,0.0

Mean time for 10 bits and 100 samples is 0.00028187279999999996.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0110110000011111001010110111111000000000011001...,0110110000011111001010110111111000000000011001...,0110110000011111001010110111111000000000011001...,100,100,400,1,0.0
1,1110101010111111101110010110010001111000000010...,1110101010111111101110010110010001111000000010...,0111,4,100,400,0,0.0
2,1100001001000110101011100001010001011001111010...,1100001001000110101011100001010001011001111010...,01,2,100,400,0,0.0
3,0110011000001001111101010010101100100010101000...,0110011000001001111101010010101100100010101000...,0110011000001001111101010010101100100010101000...,100,100,400,1,0.0
4,1010001110001011111000101011100110100100110010...,1010001110001011111000101011100110100100110010...,1010001110001011111000101011100110100100110010...,100,100,400,1,0.0
...,...,...,...,...,...,...,...,...
95,1010101010101000001110010101011011011001110100...,1010101010101000001110010101011011011001110100...,1000,4,100,400,0,0.0
96,0111110111001101101100001000000101110011110111...,0111110111001101101100001000000101110011110111...,11,2,100,400,0,0.0
97,0101111101111101111010000010111111111010110111...,0101111101111101111010000010111111111010110111...,0101111101111101111010000010111111111010110111...,100,100,400,1,0.0
98,1001011110000110000011010101011111011001001101...,1001011110000110000011010101011111011001001101...,1001011110000110000011010101011111011001001101...,100,100,400,1,0.0
99,1101101101100111100101001010110110111010011100...,1101101101100111100101001010110110111010011100...,1101101101100111100101001010110110111010011100...,100,100,400,1,0.0

Mean time for 100 bits and 100 samples is 0.0002072454.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1010000101000010111000000010010100001010001111...,1010000101000010111000000010010100001010001111...,01,2,1000,4000,0,0.000000
1,0011111101001110100111010111011000010000100101...,0011111101001110100111010111011000010000100101...,0011111101001110100111010111011000010000100101...,1000,1000,4000,1,0.000000
2,0110011101011111111010000001100010100000010100...,0110011101011111111010000001100010100000010100...,0110011101011111111010000001100010100000010100...,1000,1000,4000,1,0.000000
3,0010011110101001101000011000010001101010100001...,0010011110101001101000011000010001101010100001...,0010011110101001101000011000010001101010100001...,1000,1000,4000,1,0.002879
4,0110111111011001111110111011001010100111110110...,0110111111011001111110111011001010100111110110...,0110111111011001111110111011001010100111110110...,1000,1000,4000,1,0.000000
...,...,...,...,...,...,...,...,...
95,1100110000000110100100100101110111100101001001...,1100110000000110100100100101110111100101001001...,00,2,1000,4000,0,0.000000
96,0111110100010110010001110000010000000011111110...,0111110100010110010001110000010000000011111110...,0111110100010110010001110000010000000011111110...,1000,1000,4000,1,0.000000
97,0000010101110111111101010001101101100111000000...,0000010101110111111101010001101101100111000000...,0000010101110111111101010001101101100111000000...,1000,1000,4000,1,0.000000
98,0101010011011000001000110110001001110110111101...,0101010011011000001000110110001001110110111101...,0101010011011000001000110110001001110110111101...,1000,1000,4000,1,0.000000
99,0100010101111101111110101111000000010100111110...,0100010101111101111110101111000000010100111110...,0100010101111101111110101111000000010100111110...,1000,1000,4000,1,0.000000

Mean time for 1000 bits and 100 samples is 0.0010434721.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1010100100000101011001000010011011011000101000...,1010100100000101011001000010011011011000101000...,11,2,10000,40000,0,0.013516
1,1100110011011110100111011110010101111100111111...,1100110011011110100111011110010101111100111111...,10,2,10000,40000,0,0.004183
2,1010011011001011010100001001111010111101011001...,1010011011001011010100001001111010111101011001...,1010011011001011010100001001111010111101011001...,10000,10000,40000,1,0.000000
3,1000100010101010000000010001111011110000100001...,1000100010101010000000010001111011110000100001...,01,2,10000,40000,0,0.013143
4,1010000110100111001011111111001011100111111111...,1010000110100111001011111111001011100111111111...,10,2,10000,40000,0,0.000000
...,...,...,...,...,...,...,...,...
95,0011111000111001011010101000111010000010110111...,0011111000111001011010101000111010000010110111...,0011111000111001011010101000111010000010110111...,10000,10000,40000,1,0.000000
96,1110011110011011011001111111100101101111111000...,1110011110011011011001111111100101101111111000...,1110011110011011011001111111100101101111111000...,10000,10000,40000,1,0.012949
97,0010011110111101010000000001100100111100111001...,0010011110111101010000000001100100111100111001...,0010011110111101010000000001100100111100111001...,10000,10000,40000,1,0.005842
98,0100101000111110101001000100101011100101010001...,0100101000111110101001000100101011100101010001...,0100101000111110101001000100101011100101010001...,10000,10000,40000,1,0.000000
99,1110010110111100110001010100111001011111010001...,1110010110111100110001010100111001011111010001...,1110010110111100110001010100111001011111010001...,10000,10000,40000,1,0.011215

Mean time for 10000 bits and 100 samples is 0.0051818109.