Copyright Tarter, Herasymov, Priebracha 2025

Finding minimal recurrence:

In [2]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0


def backTest(upper):
    out = pd.DataFrame(columns=['BitCount', 'sampleSize', 'Time'])

    for i in range(upper-1):
        digitLength = 2#10**(i+1)
        sampleSize = 100

        tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
        for k in range(sampleSize): #generate the test cases
            tests.loc[k] = genSeq(4,digitLength)
        testList = tests['Test Case'].to_list() #send each test case to a list

        def decode(sequence, tests, l):
            n = len(sequence) #get length
            factors = []
            for j in range(n): #find factors ### O(n)
                if n % (j+1) == 0:
                    factors += [n/(j+1)]
            factors.sort()
            options = {}
            for i in range(len(factors)-1,0,-1): ####O(log(n))
                rec = sequence[int(n - factors[i]):n] #isolate the recurrence
                trial = f'{rec}'*2 #concat to make the trial
                if trial == str(tests.loc[l,'Test Case'])[int(n - 2*factors[i]):n]: #tests if the trial works
                    options.update({len(rec):rec})
            return options[min(options)]

        l = 0
        for sequence in testList:
            start = time.time()
            tests.loc[l,'Solution'] = decode(sequence,tests,l)
            end = time.time()
            tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
            tests.loc[l,'Solution Length'] = len(str(tests.loc[l,'Solution']))
            tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
            tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])
            if tests.loc[l,'Reccurence'] == tests.loc[l,'Solution']:
                tests.loc[l,'Works?'] = 1
            l += 1

        display(tests)
        out.loc[i]=[digitLength, sampleSize, np.mean(tests['Time'])]
        print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
    return out

out = backTest(2)
display(out)

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,01010101,01,01,2,2,8,1,0.0
1,01010101,01,01,2,2,8,1,0.0
2,10101010,10,10,2,2,8,1,0.0
3,00000000,00,00,2,2,8,1,0.0
4,10101010,10,10,2,2,8,1,0.0
...,...,...,...,...,...,...,...,...
95,00000000,00,00,2,2,8,1,0.0
96,01010101,01,01,2,2,8,1,0.0
97,00000000,00,00,2,2,8,1,0.0
98,10101010,10,10,2,2,8,1,0.0
99,00000000,00,00,2,2,8,1,0.0

Mean time for 2 bits and 100 samples is 0.0001995444.

   BitCount  sampleSize    Time
0       2.0       100.0  0.0002