Copyright Tarter, Herasymov, Priebracha 2025

Finding minimal recurrence:

In [5]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0


def backTest(upper):
    out = pd.DataFrame(columns=['BitCount', 'sampleSize', 'Time'])

    for i in range(upper-1):
        digitLength = 10**(i+1)
        sampleSize = 100

        tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
        for k in range(sampleSize): #generate the test cases
            tests.loc[k] = genSeq(4,digitLength)
        testList = tests['Test Case'].to_list() #send each test case to a list

        def decode(sequence, tests, l):
            n = len(sequence) #get length
            factors = []
            for j in range(n): #find factors ### O(n)
                if n % (j+1) == 0:
                    factors += [n/(j+1)]
            factors.sort()
            options = {}
            for i in range(len(factors)-1,0,-1): ####O(log(n))
                rec = sequence[int(n - factors[i]):n] #isolate the recurrence
                trial = f'{rec}'*2 #concat to make the trial
                if trial == str(tests.loc[l,'Test Case'])[int(n - 2*factors[i]):n]: #tests if the trial works
                    options.update({len(rec):rec})
            return options[min(options)]

        l = 0
        for sequence in testList:
            start = time.time()
            tests.loc[l,'Solution'] = decode(sequence,tests,l)
            end = time.time()
            tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
            tests.loc[l,'Solution Length'] = len(str(tests.loc[l,'Solution']))
            tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
            tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])
            if tests.loc[l,'Reccurence'] == tests.loc[l,'Solution']:
                tests.loc[l,'Works?'] = 1
            l += 1

        display(tests)
        out.loc[i]=[digitLength, sampleSize, np.mean(tests['Time'])]
        print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
    return out

out = backTest(5)
display(out)

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0011010000001101000000110100000011010000,0011010000,00,2,10,40,0,0.0
1,1101101110110110111011011011101101101110,1101101110,1101101110,10,10,40,1,0.0
2,1110111010111011101011101110101110111010,1110111010,10,2,10,40,0,0.0
3,0010001011001000101100100010110010001011,0010001011,0010001011,10,10,40,1,0.0
4,0001100100000110010000011001000001100100,0001100100,0001100100,10,10,40,1,0.0
...,...,...,...,...,...,...,...,...
95,0001110111000111011100011101110001110111,0001110111,0111,4,10,40,0,0.0
96,0101101011010110101101011010110101101011,0101101011,01011,5,10,40,0,0.0
97,1000111011100011101110001110111000111011,1000111011,1000111011,10,10,40,1,0.0
98,0010110010001011001000101100100010110010,0010110010,0010110010,10,10,40,1,0.0
99,0110100010011010001001101000100110100010,0110100010,0110100010,10,10,40,1,0.0

Mean time for 10 bits and 100 samples is 0.0004526878.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0101110110010010111000011011000110101111101110...,0101110110010010111000011011000110101111101110...,00,2,100,400,0,0.000000
1,0000010001100000100111011000101101011101010011...,0000010001100000100111011000101101011101010011...,1000,4,100,400,0,0.000000
2,0100010001010001100111110000010101011001010100...,0100010001010001100111110000010101011001010100...,0100010001010001100111110000010101011001010100...,100,100,400,1,0.000000
3,1100000110111110101000010101001000001000100100...,1100000110111110101000010101001000001000100100...,1100000110111110101000010101001000001000100100...,100,100,400,1,0.000000
4,1010001001010010100001100111011000000011000111...,1010001001010010100001100111011000000011000111...,1101,4,100,400,0,0.000000
...,...,...,...,...,...,...,...,...
95,1010101000111100110111100001000101001000000110...,1010101000111100110111100001000101001000000110...,1010101000111100110111100001000101001000000110...,100,100,400,1,0.000000
96,0110111001011010010011001011010010000111101101...,0110111001011010010011001011010010000111101101...,01,2,100,400,0,0.000000
97,1101101000000101110100001001000011111000010010...,1101101000000101110100001001000011111000010010...,1101101000000101110100001001000011111000010010...,100,100,400,1,0.000000
98,0100001010001101101100100101110100110001100101...,0100001010001101101100100101110100110001100101...,0010,4,100,400,0,0.000000
99,1001000100001001111100000000011010011001111110...,1001000100001001111100000000011010011001111110...,1001000100001001111100000000011010011001111110...,100,100,400,1,0.001112

Mean time for 100 bits and 100 samples is 0.00037974369999999995.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0000000111110101100100011010010101111110101000...,0000000111110101100100011010010101111110101000...,00,2,1000,4000,0,0.000000
1,0001111110001110000101110001100111110101101000...,0001111110001110000101110001100111110101101000...,0001111110001110000101110001100111110101101000...,1000,1000,4000,1,0.001305
2,0011000100011100100001000111111110111001010001...,0011000100011100100001000111111110111001010001...,0011000100011100100001000111111110111001010001...,1000,1000,4000,1,0.000000
3,1001111100010110000110001101101001110100100001...,1001111100010110000110001101101001110100100001...,10,2,1000,4000,0,0.000000
4,0101011000100001100100111110011111001011100110...,0101011000100001100100111110011111001011100110...,0101011000100001100100111110011111001011100110...,1000,1000,4000,1,0.000000
...,...,...,...,...,...,...,...,...
95,1110110000111110101000110010111110111011010111...,1110110000111110101000110010111110111011010111...,1110110000111110101000110010111110111011010111...,1000,1000,4000,1,0.000000
96,1000011010111101100111110111001110000111000110...,1000011010111101100111110111001110000111000110...,00,2,1000,4000,0,0.007349
97,1010100101010011111000110100111011100100000001...,1010100101010011111000110100111011100100000001...,1010100101010011111000110100111011100100000001...,1000,1000,4000,1,0.000000
98,1011010111001111011011100001111101000011101000...,1011010111001111011011100001111101000011101000...,1011010111001111011011100001111101000011101000...,1000,1000,4000,1,0.006182
99,0011010101101101010000001110011010001100010101...,0011010101101101010000001110011010001100010101...,0011010101101101010000001110011010001100010101...,1000,1000,4000,1,0.000349

Mean time for 1000 bits and 100 samples is 0.0011992933999999998.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0001110111001100000011010000110001101010100001...,0001110111001100000011010000110001101010100001...,01,2,10000,40000,0,0.004947
1,0000101110010110001010001101001101010010110110...,0000101110010110001010001101001101010010110110...,0010,4,10000,40000,0,0.000000
2,0010101111011001101011001111000011100011111101...,0010101111011001101011001111000011100011111101...,11,2,10000,40000,0,0.007896
3,1101100011111011010000001101010001100100111001...,1101100011111011010000001101010001100100111001...,1101100011111011010000001101010001100100111001...,10000,10000,40000,1,0.000000
4,0001101001101110011100100110001101111111011110...,0001101001101110011100100110001101111111011110...,0001101001101110011100100110001101111111011110...,10000,10000,40000,1,0.005345
...,...,...,...,...,...,...,...,...
95,1010110010000110011111000110101000111000101010...,1010110010000110011111000110101000111000101010...,1010110010000110011111000110101000111000101010...,10000,10000,40000,1,0.008793
96,1100000011100000010010101101010001110101111100...,1100000011100000010010101101010001110101111100...,1100000011100000010010101101010001110101111100...,10000,10000,40000,1,0.000000
97,0101110110010001101011111111101111001111100001...,0101110110010001101011111111101111001111100001...,0101110110010001101011111111101111001111100001...,10000,10000,40000,1,0.007766
98,0110000110100001101010100001011001101001101011...,0110000110100001101010100001011001101001101011...,0110000110100001101010100001011001101001101011...,10000,10000,40000,1,0.000000
99,0010011011011011010110101110111111010100110101...,0010011011011011010110101110111111010100110101...,0010011011011011010110101110111111010100110101...,10000,10000,40000,1,0.008790

Mean time for 10000 bits and 100 samples is 0.0055515524.

   BitCount  sampleSize      Time
0      10.0       100.0  0.000453
1     100.0       100.0  0.000380
2    1000.0       100.0  0.001199
3   10000.0       100.0  0.005552