Copyright Tarter, Herasymov, Priebracha 2025

Finding minimal recurrence:

In [8]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0


def backTest(upper):
    out = pd.DataFrame(columns=['BitCount', 'sampleSize', 'Time'])

    for i in range(upper-1):
        digitLength = 10**(i+1)
        sampleSize = 100

        tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
        for k in range(sampleSize): #generate the test cases
            tests.loc[k] = genSeq(4,digitLength)
        testList = tests['Test Case'].to_list() #send each test case to a list

        def decode(sequence, tests, l):
            n = len(sequence) #get length
            factors = []
            for j in range(n): #find factors ### O(n)
                if n % (j+1) == 0:
                    factors += [n/(j+1)]
            factors.sort()
            options = {}
            for i in range(len(factors)-1,0,-1): ####O(log(n))
                rec = sequence[int(n - factors[i]):n] #isolate the recurrence
                trial = f'{rec}'*int(n//factors[i]) #concat to make the trial
                if trial == str(tests.loc[l,'Test Case']): #tests if the trial works
                    options.update({len(rec):rec})
            return options[min(options)]

        l = 0
        for sequence in testList:
            start = time.time()
            tests.loc[l,'Solution'] = decode(sequence,tests,l)
            end = time.time()
            tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
            tests.loc[l,'Solution Length'] = len(str(tests.loc[l,'Solution']))
            tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
            tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])
            if tests.loc[l,'Reccurence'] == tests.loc[l,'Solution']:
                tests.loc[l,'Works?'] = 1
            l += 1

        display(tests)
        out.loc[i]=[digitLength, sampleSize, np.mean(tests['Time'])]
        print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
    return out

out = backTest(5)
display(out)

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0001001010000100101000010010100001001010,0001001010,0001001010,10,10,40,1,0.001822
1,0001101111000110111100011011110001101111,0001101111,0001101111,10,10,40,1,0.000000
2,0110101010011010101001101010100110101010,0110101010,0110101010,10,10,40,1,0.000000
3,0010010111001001011100100101110010010111,0010010111,0010010111,10,10,40,1,0.000000
4,0010010101001001010100100101010010010101,0010010101,0010010101,10,10,40,1,0.000000
...,...,...,...,...,...,...,...,...
95,1101001100110100110011010011001101001100,1101001100,1101001100,10,10,40,1,0.000000
96,0100111000010011100001001110000100111000,0100111000,0100111000,10,10,40,1,0.000000
97,0101101000010110100001011010000101101000,0101101000,0101101000,10,10,40,1,0.000000
98,1010000100101000010010100001001010000100,1010000100,1010000100,10,10,40,1,0.000000
99,1100000101110000010111000001011100000101,1100000101,1100000101,10,10,40,1,0.000000

Mean time for 10 bits and 100 samples is 0.00036702640000000003.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1101011000110001010101100010111001000001111101...,1101011000110001010101100010111001000001111101...,1101011000110001010101100010111001000001111101...,100,100,400,1,0.0
1,0010010101000000010011011100101011100001100101...,0010010101000000010011011100101011100001100101...,0010010101000000010011011100101011100001100101...,100,100,400,1,0.0
2,1100101111111111100101000100010101011101110100...,1100101111111111100101000100010101011101110100...,1100101111111111100101000100010101011101110100...,100,100,400,1,0.0
3,0111100100101110010011000100000111000101100011...,0111100100101110010011000100000111000101100011...,0111100100101110010011000100000111000101100011...,100,100,400,1,0.0
4,0101000000111110011111111001011101011110101110...,0101000000111110011111111001011101011110101110...,0101000000111110011111111001011101011110101110...,100,100,400,1,0.0
...,...,...,...,...,...,...,...,...
95,0011101011000010000001010001100101000101111100...,0011101011000010000001010001100101000101111100...,0011101011000010000001010001100101000101111100...,100,100,400,1,0.0
96,1010001011010001000001110010001101111011100010...,1010001011010001000001110010001101111011100010...,1010001011010001000001110010001101111011100010...,100,100,400,1,0.0
97,1110000000001010011110111000000011010000100011...,1110000000001010011110111000000011010000100011...,1110000000001010011110111000000011010000100011...,100,100,400,1,0.0
98,0011111110110101011101100100000000100010110101...,0011111110110101011101100100000000100010110101...,0011111110110101011101100100000000100010110101...,100,100,400,1,0.0
99,1110001011001000001110000111100011100010010110...,1110001011001000001110000111100011100010010110...,1110001011001000001110000111100011100010010110...,100,100,400,1,0.0

Mean time for 100 bits and 100 samples is 9.7952e-05.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1100000001100100110101001110111101001010110110...,1100000001100100110101001110111101001010110110...,1100000001100100110101001110111101001010110110...,1000,1000,4000,1,0.000000
1,0001111110110010101001110100101111011100000110...,0001111110110010101001110100101111011100000110...,0001111110110010101001110100101111011100000110...,1000,1000,4000,1,0.000000
2,1011100010110011110110101010010000001101110010...,1011100010110011110110101010010000001101110010...,1011100010110011110110101010010000001101110010...,1000,1000,4000,1,0.010693
3,1001000111011001110111000000011000110001111111...,1001000111011001110111000000011000110001111111...,1001000111011001110111000000011000110001111111...,1000,1000,4000,1,0.002611
4,1001001110111110011011110100001001010111010101...,1001001110111110011011110100001001010111010101...,1001001110111110011011110100001001010111010101...,1000,1000,4000,1,0.000919
...,...,...,...,...,...,...,...,...
95,1001100011101100101010011101000000010110111100...,1001100011101100101010011101000000010110111100...,1001100011101100101010011101000000010110111100...,1000,1000,4000,1,0.000000
96,0111010001010010011111101010101111111100001011...,0111010001010010011111101010101111111100001011...,0111010001010010011111101010101111111100001011...,1000,1000,4000,1,0.000000
97,0010000011110110000001101110001000000001100011...,0010000011110110000001101110001000000001100011...,0010000011110110000001101110001000000001100011...,1000,1000,4000,1,0.002563
98,0101111011000011001001000000110110011001000010...,0101111011000011001001000000110110011001000010...,0101111011000011001001000000110110011001000010...,1000,1000,4000,1,0.001792
99,0100000111000111010011011100111001101010011001...,0100000111000111010011011100111001101010011001...,0100000111000111010011011100111001101010011001...,1000,1000,4000,1,0.000000

Mean time for 1000 bits and 100 samples is 0.0010165953.

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0100010000100100101111110101101011101111110011...,0100010000100100101111110101101011101111110011...,0100010000100100101111110101101011101111110011...,10000,10000,40000,1,0.009352
1,1110110101011111100111111110011111000011000110...,1110110101011111100111111110011111000011000110...,1110110101011111100111111110011111000011000110...,10000,10000,40000,1,0.006603
2,1110010101000100001010101001100111101000101001...,1110010101000100001010101001100111101000101001...,1110010101000100001010101001100111101000101001...,10000,10000,40000,1,0.000000
3,1011101000011010111100011010001110011000010011...,1011101000011010111100011010001110011000010011...,1011101000011010111100011010001110011000010011...,10000,10000,40000,1,0.009266
4,0011010001110000011100001000001010101110110010...,0011010001110000011100001000001010101110110010...,0011010001110000011100001000001010101110110010...,10000,10000,40000,1,0.007210
...,...,...,...,...,...,...,...,...
95,0010001110110010010001110011110001100100001100...,0010001110110010010001110011110001100100001100...,0010001110110010010001110011110001100100001100...,10000,10000,40000,1,0.013119
96,0101010110100110100101000000100011111011101100...,0101010110100110100101000000100011111011101100...,0101010110100110100101000000100011111011101100...,10000,10000,40000,1,0.000000
97,1101000110010100001100000111100010011111100011...,1101000110010100001100000111100010011111100011...,1101000110010100001100000111100010011111100011...,10000,10000,40000,1,0.000000
98,1111001000001100000011010011011100110100111100...,1111001000001100000011010011011100110100111100...,1111001000001100000011010011011100110100111100...,10000,10000,40000,1,0.000000
99,1001110000100111011000010111011110011101001100...,1001110000100111011000010111011110011101001100...,1001110000100111011000010111011110011101001100...,10000,10000,40000,1,0.005266

Mean time for 10000 bits and 100 samples is 0.0045417596.

   BitCount  sampleSize      Time
0      10.0       100.0  0.000367
1     100.0       100.0  0.000098
2    1000.0       100.0  0.001017
3   10000.0       100.0  0.004542