Copyright Tarter, Herasymov, Priebracha 2025

Non-minimal finding algorithm:

In [13]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0

digitLength = 10000
sampleSize = 10

tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
for k in range(sampleSize): #generate the test cases
    tests.loc[k] = genSeq(5,digitLength)


testList = tests['Test Case'].to_list() #send each test case to a list

def decode(sequence):
    n = len(sequence) #get length
    factors = []
    for j in range(n-2): #find factors
        if n % (j+2) == 0:
            factors += [n/(j+2)]
    
    mFact = max(factors) #pick the largest factor
    rec = sequence[int(n - mFact + 2):n] #isolate the recurrence
    return rec, int(n-mFact+2), n


l = 0
for sequence in testList:
    start = time.time()
    tests.loc[l,'Solution'], repets, n = decode(sequence)
    end = time.time()

    tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
    tests.loc[l,'Solution Length'] = len(tests.loc[l,'Solution'])
    tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
    tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])

    if str(tests.loc[l,'Test Case'])[repets:n] == tests.loc[l,'Solution']: #checks our work
        tests.loc[l,'Works?'] = 1
    
    l += 1


display(tests)
print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
print(f'If this is not 1, we have a big problem: {sum(tests['Works?'])/len(tests['Works?'])}')

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,0111010010000011001100011010100100101001111111...,0111010010000011001100011010100100101001111111...,1101001000000110110110010111000011010100110110...,24998,10000,50000,1,0.015932
1,1000100010101001000011101101100110100101010101...,1000100010101001000011101101100110100101010101...,0110000000100001110110101100110111000101101000...,24998,10000,50000,1,0.000000
2,1010101101011110111100001000101110011001111100...,1010101101011110111100001000101110011001111100...,1100100110011010111000111010011011100010110011...,24998,10000,50000,1,0.000000
3,1111001011100101011010001001010011000100010010...,1111001011100101011010001001010011000100010010...,0101101111010110000111010100111100011110110110...,24998,10000,50000,1,0.015096
4,0001101011110000001100111101001000011100111010...,0001101011110000001100111101001000011100111010...,0100011101010110011111101100110010011100001111...,24998,10000,50000,1,0.000000
5,1000101001100110100100110010001110011111101100...,1000101001100110100100110010001110011111101100...,0000011111011001100100010000011110011110000101...,24998,10000,50000,1,0.000000
6,1111001110011010000110010110110110110101000000...,1111001110011010000110010110110110110101000000...,1101000101101100000010100001011101001011100000...,24998,10000,50000,1,0.000000
7,1101100011000000010010100110100011010010000111...,1101100011000000010010100110100011010010000111...,0001000101001111000100010111111111110011100000...,24998,10000,50000,1,0.015861
8,0000101110010001101110101100010000110101101001...,0000101110010001101110101100010000110101101001...,0010001101111011111001011000110000110000110001...,24998,10000,50000,1,0.002588
9,0100111011001000010110111000101100001100101100...,0100111011001000010110111000101100001100101100...,0010100010000000010111100101001000010110010101...,24998,10000,50000,1,0.000000

Mean time for 10000 bits and 10 samples is 0.0049477110000000005.
If this is not 1, we have a big problem: 1.0

Finding minimal recurrence:

In [14]:
import pandas as pd 
import numpy as np 
import math 
import random as rd
import warnings
import time
warnings.filterwarnings('ignore')

def genRec(length): #generate the recurrence for the test case
    rec = ''
    for i in range(length):
        rec += f'{rd.randint(0,1)}'
    return rec

def genSeq(slength, rlength): #generate the full sequence for the test case
    seq = ''
    rec = genRec(rlength)
    for i in range(slength):
        seq += rec
    return seq, rec, 0, 0, 0, 0, 0, 0

digitLength = 10000
sampleSize = 10

tests = pd.DataFrame(columns=['Test Case', 'Reccurence', 'Solution', 'Solution Length', 'True Length', 'Test Case Length', 'Works?', 'Time']) #initialize the dataframe
for k in range(sampleSize): #generate the test cases
    tests.loc[k] = genSeq(5,digitLength)


testList = tests['Test Case'].to_list() #send each test case to a list

def decode(sequence):
    n = len(sequence) #get length
    factors = []
    for j in range(n-2): #find factors
        if n % (j+2) == 0:
            factors += [n/(j+2)]
    
    mFact = max(factors) #pick the largest factor
    rec = sequence[int(n - mFact + 2):n] #isolate the recurrence
    return rec, int(n-mFact+2), n


l = 0
for sequence in testList:
    start = time.time()
    tests.loc[l,'Solution'], repets, n = decode(sequence)
    end = time.time()

    tests.loc[l,'Time'] = round(end - start,8)#log time for complexity
    tests.loc[l,'Solution Length'] = len(tests.loc[l,'Solution'])
    tests.loc[l,'True Length'] = len(tests.loc[l,'Reccurence'])
    tests.loc[l,'Test Case Length'] = len(tests.loc[l,'Test Case'])

    if str(tests.loc[l,'Test Case'])[repets:n] == tests.loc[l,'Solution']: #checks our work
        tests.loc[l,'Works?'] = 1
    
    l += 1


display(tests)
print(f'Mean time for {digitLength} bits and {sampleSize} samples is {np.mean(tests['Time'])}.')
print(f'If this is not 1, we have a big problem: {sum(tests['Works?'])/len(tests['Works?'])}')

,Test Case,Reccurence,Solution,Solution Length,True Length,Test Case Length,Works?,Time
0,1010001011111101110011111011100010000011110111...,1010001011111101110011111011100010000011110111...,1101110010000010100011010101111000001110110111...,24998,10000,50000,1,0.000000
1,1100100101000010101011101110010100110000011100...,1100100101000010101011101110010100110000011100...,0100010110011001100101111101100000010110000100...,24998,10000,50000,1,0.012521
2,1111001001011011111110011001111000000100001110...,1111001001011011111110011001111000000100001110...,0111011001101000010000110111000010100100001011...,24998,10000,50000,1,0.000000
3,0000101001100010000010101001101000000100101110...,0000101001100010000010101001101000000100101110...,1110011000111001100110001111100000001100010100...,24998,10000,50000,1,0.000000
4,1101011000110100101011001110001100000001011001...,1101011000110100101011001110001100000001011001...,1011111111000111001001101000000000010001110101...,24998,10000,50000,1,0.000000
5,0100001000000000000011110100100010110001110011...,0100001000000000000011110100100010110001110011...,1101010011010111101100010001100000000111110101...,24998,10000,50000,1,0.015935
6,0111110011010011011101100000001001010110100000...,0111110011010011011101100000001001010110100000...,0001001111000011100101011100101010011000000001...,24998,10000,50000,1,0.000000
7,0001110011011111001011110000101111010100101100...,0001110011011111001011110000101111010100101100...,1001101001011101100111001111010101010111000111...,24998,10000,50000,1,0.000000
8,1100110010101101101000110001110100110000011011...,1100110010101101101000110001110100110000011011...,0101100011000000100101011100100011111011111001...,24998,10000,50000,1,0.000000
9,0101011110001011001101010010010111011111111010...,0101011110001011001101010010010111011111111010...,1101110111101010110101110010011110110111111101...,24998,10000,50000,1,0.000000

Mean time for 10000 bits and 10 samples is 0.002845574.
If this is not 1, we have a big problem: 1.0